export const dataBerita = [
    {
        date: new Date('2024-06-08'),
        author: 'John Doe',
        title: 'Mentan Amran dan KASAD Jenderal Maruli Panen Bawang Merah di Kawasan Urban Farming',
        ringkasan: 'Menteri Pertanian (Mentan) Andi Amran Sulaiman bersama Kepala Staf Angkatan Darat (KASAD), Jenderal TNI, Maruli Simanjuntak melakukan panen bawang merah di lahan urban farming Korem 051/WKT Kodam Jaya di Desa Wanajaya, Cibitung, Bekasi.',
        deskripsi: 'Cibitung, (11/6) Menteri Pertanian (Mentan) Andi Amran Sulaiman bersama Kepala Staf Angkatan Darat (KASAD), Jenderal TNI, Maruli Simanjuntak melakukan panen bawang merah di lahan urban farming Korem 051/WKT Kodam Jaya di Desa Wanajaya, Cibitung, Bekasi. Panen di lahan perkotaan seluas 13 hektar ini merupakan sinergi antara Kementerian Pertanian (Kementan) bersama TNI AD dalam memperkuat penyediaan pangan dan mengendalikan inflasi di tengah ancaman dampak perubahan iklim. <br/> ',
        gambar: '/berita/1.jpeg',
    },
    {
        date: new Date('2024-06-05'),
        author: 'Jane Smith',
        title: 'Kementerian Pertanian Luncurkan Program Baru untuk Petani',
        ringkasan: 'Kementerian Pertanian meluncurkan program baru yang bertujuan untuk meningkatkan produktivitas dan pendapatan petani di seluruh Indonesia.',
        deskripsi: '',
        gambar: '/berita/2.jpeg',
    },
    {
        date: new Date('2024-06-02'),
        author: 'Michael Johnson',
        title: 'Subsidi Pupuk Ditingkatkan untuk Mendukung Petani',
        ringkasan: 'Pemerintah meningkatkan subsidi pupuk untuk membantu petani menghadapi kenaikan biaya produksi dan menjaga ketahanan pangan nasional.',
        deskripsi: '',
        gambar: '/berita/3.jpeg',
    },
    {
        date: new Date('2024-05-29'),
        author: 'Emily Davis',
        title: 'Kementerian Pertanian Kembangkan Teknologi Pertanian Presisi',
        ringkasan: 'Kementerian Pertanian bekerja sama dengan perguruan tinggi dan institusi penelitian untuk mengembangkan teknologi pertanian presisi guna meningkatkan efisiensi dan produktivitas pertanian.',
        deskripsi: '',
        gambar: '/berita/4.jpeg',
    },
    {
        date: new Date('2024-05-26'),
        author: 'David Wilson',
        title: 'Pameran Pertanian Nasional Digelar di Jakarta',
        ringkasan: 'Pameran Pertanian Nasional yang diselenggarakan di Jakarta menampilkan inovasi terbaru dalam bidang pertanian dan memamerkan produk-produk unggulan dari petani lokal.',
        deskripsi: '',
        gambar: '/berita/5.jpeg',
    },
    {
        date: new Date('2024-05-23'),
        author: 'Sophia Thompson',
        title: 'Kementerian Pertanian Dukung Pengembangan Pertanian Organik',
        ringkasan: 'Kementerian Pertanian mendukung pengembangan pertanian organik dengan memberikan pelatihan dan insentif bagi petani yang mengadopsi praktik pertanian ramah lingkungan.',
        deskripsi: '',
        gambar: '/berita/6.jpeg',
    },
    {
        date: new Date('2024-05-20'),
        author: 'William Anderson',
        title: 'Kebijakan Baru untuk Melindungi Lahan Pertanian',
        ringkasan: 'Pemerintah mengeluarkan kebijakan baru untuk melindungi lahan pertanian dari alih fungsi lahan dan menjaga ketahanan pangan nasional.',
        deskripsi: '',
        gambar: '/berita/7.jpeg',
    },
    {
        date: new Date('2024-05-17'),
        author: 'Olivia Martinez',
        title: 'Kementerian Pertanian Dorong Pengembangan Agrowisata',
        ringkasan: 'Kementerian Pertanian mendorong pengembangan agrowisata di seluruh Indonesia untuk meningkatkan pendapatan petani dan mempromosikan pariwisata berkelanjutan.',
        deskripsi: '',
        gambar: '/berita/8.jpeg',
    },
    {
        date: new Date('2024-05-14'),
        author: 'James Robinson',
        title: 'Pelatihan Manajemen Usaha Tani bagi Petani Muda',
        ringkasan: 'Kementerian Pertanian mengadakan pelatihan manajemen usaha tani bagi petani muda untuk membekali mereka dengan keterampilan bisnis yang diperlukan dalam mengelola usaha pertanian yang sukses.',
        deskripsi: '',
        gambar: '/berita/9.jpeg',
    },
    {
        date: new Date('2024-05-11'),
        author: 'Ava Rodriguez',
        title: 'Kementerian Pertanian Luncurkan Aplikasi Mobile untuk Petani',
        ringkasan: 'Kementerian Pertanian meluncurkan aplikasi mobile yang menyediakan informasi terkini tentang harga pasar, cuaca, dan rekomendasi pertanian untuk membantu petani dalam mengambil keputusan yang tepat.',
        deskripsi: '',
        gambar: '/berita/10.jpeg',
    }
];